### ISSUE TITLE
Dropwizard 0.8

### ISSUE THREAD

**Issue by samklr** [jaredstehler/dropwizard-guice#10]
Hi, I've been trying to use this nice project. But it seems that it requires dependecies from an old version of Jetty. And adding a dependency to that version creates mayhem. 
Any idea how I can upgrade this to he new dropwizard with jersey 2.

**Comment by jaredstehler** [comment]
let me see about upgrading this lib to dw 0.8

**Comment by jaredstehler** [comment]
https://github.com/jaredstehler/dropwizard-guice/commit/466f7030443c06db4dcb33c7c34bfb69492a0c76 upgrades this lib to dw 8, which includes jersey 2. Published to mvn central as 0.8.1, 0.8.2-SNAPSHOT.

**Comment by samklr** [comment]
Awesome. Thanks.
